export const  lang= {
    en : {
        "beaches" :"Beaches",
        "name" : "Name",
        "mountains":"Mountains",
        "forests" : "Forests",
        "towns": "Towns",
        "welcome" : "Welcome",
        "add new hiking" : "Add New Hiking",
        "hike name" : "Hike Name",
        "hike location" : "Hike Location",
        "hike duration" : "Hike Duration",
        "hike category" : "Hike Category",
        "hike price" : "Hike Price",
        "hike description":"Hike Description",
        "submit" :"Submit",
        "profile" : "Profile",
        "edit profile": "Edit Profile",
        "inbox" : "Inbox",
        "logout" : "Logout",
        "language" : "Language",
        "update profile" : "Update Profile",
        "full name" : "Full Name",
        "company name" : "Company Name",
        "tin no" : "Tin No",
        "registration no" : "Company Registration No",
        "how many trips" : "How Many Trips you Organized Before?",
        "where do you hear it from" : "Where did you hear it from",
        "About Your Company Description":"About Your Company Description",
        "br" : "Birr",
        "category" : "Category",
        "email address" : "Email Address",
        "password" : "Password",
        "forgot password" :"Forgot Password ?",
        "login" : "Login",
        "Dont have an account" : "Don't have An Account ?",     
        "or":"Or",
        "sign up" : "Sign Up", 
        "already have an account" : "Already Have An Account ?", 
        "lets get started" : "Lets Get Started", 
        "About" : "About",
        "Make Reservation" :"Make Reservation",
        "phone" :"Phone Number"

    },
    am:{
        "beaches" :"የባህር ዳርቻዎች",
        "name" : "ስም",
        "mountains":"ተራሮች",
        "forests" : "ደኖች",
        "towns": "ከተሞች",
        "welcome" : "እንኳን ደህና መጣህ",
        "add new hiking" : "አዲስ የእግር ጉዞ ጨምር",
        "hike name" : "የእግር ጉዞ ስም",
        "hike location" : "የእግር ጉዞ ቦታ",
        "hike duration" : "የእግር ጉዞ ቆይታ",
        "hike category" : "የእግር ጉዞ ምድብ",
        "hike price" : "የዋጋ ጭማሪ",
        "hike description":"የእግር ጉዞ መግለጫ",
        "submit" :"አስገባ",
        "profile" : "መገለጫ",
        "edit profile": "መገለጫ አርትዕ",
        "inbox" : "ውይይት",
        "logout" : "ውጣ",
        "language" : "ቋንቋ",
        "update profile" : "መገለጫ አዘምን",
        "full name" : "ሙሉ ስም",
        "company name" : "የኩባንያ ስም",
        "tin no" : "ቲን ቁጥር",
        "registration no" : "የኩባንያ ምዝገባ ቁጥር",
        "how many trips" : "ከዚህ በፊት ምን ያህል ጉዞዎችን አደራጅተሃል?",
        "where do you hear it from" : "ከየት ነው የሰማኸው",
        "about":"ስለ ኩባንያዎ መግለጫ",
        "br" : "ብር",
        "category" : "ምድብ",
        "email address" : "የኢሜል አድራሻ",
        "password" : "የይለፍ ቃል",
        "forgot password" :"የይለፍ ቃል ረሱ ?",
        "login" : "ግባ",
        "Dont have an account" : "መለያ የለዎትም ?",     
        "or":"ወይም",
        "sign up" : "ይመዝገቡ", 
        "already have an account" : "አስቀድሞ መለያ አለህ ?", 
        "lets get started" : "እንጀምር", 
          "About" : "ስለ ቦታው",
        "Make Reservation" :"ቦታ ማስያዝ",
        "phone" :"ስልክ ቁጥር"

    },
    or : {
        "beaches" :"Qarqara galaanaa",
        "name" : "Maqaa",
        "mountains":"Gaarreen",
        "forests" : "bosona keessaa",
        "towns": "Magaalota",
        "welcome" : "Baga nagaan dhufte",
        "add new hiking" : "Dabalaa Haaraa Hiking",
        "hike name" : "Maqaa Hike",
        "hike location" : "Bakka Hike",
        "hike duration" : "Turtii Hike",
        "hike category" : "Hike Category",
        "hike price" : "Gatii Dabaluu",
        "hike description":"Ibsa Hike",
        "submit" :"Galchuu",
        "profile" : "Ibsama",
        "edit profile": "Profaayilii Gulaali",
        "inbox" : "waliin dubbii",
        "logout" : "Ba'i",
        "language" : "Afaan",
        "update profile" : "Profaayilii Fooyyessi",
        "full name" : "Maqaa Guutuu",
        "company name" : "Maqaa Dhaabbataa",
        "tin no" : "Tin Lakk",
        "registration no" : "Galmee Dhaabbataa Lakk",
        "how many trips" : "Imala Meeqa Dura Qindeessite ?",
        "where do you hear it from" : "Eessaa dhageessanii",
        "about":"Waa'ee Ibsa Dhaabbata Keessanii",
        "br" : "Birrii",
        "category" : "Ramaddii",
        "email address" : "Teessoo Imeelii",
        "password" : "Jecha iccitii",
        "forgot password" :"Password dagadheera ?",
        "login" : "Galmaa'i",
        "Dont have an account" : "Akkaawuntii hin qabaatin ?",     
        "or":"yookaan",
        "sign up" : "Galmaa'i", 
        "already have an account" : "Duraanis Akkaawuntii Qabadhaa ?", 
        "lets get started" : "Haa Jalqabnu", 
            "About" : "Waa'ee",
        "Make Reservation" :"Reservation Godhi",
        "phone" :"lakkoofsa bilbilaa"
        },
      
}
   